### ISSUE TITLE
FR: Use color pallete from Terminal

### ISSUE THREAD

**Issue by azzamsa** [chaqchase/lla#79]
Hi, 

I have many modified themes for my personal use. I defined them in [Wezterm's colors](https://wezfurlong.org/wezterm/config/appearance.html). Unfortunately, unlike `eza` the `default` options in `lla` doesn't use colors from the terminal. 

IMO, It will be very tedious to port all theme to `lla`. Why not just provide the option to fetch colors from Terminal?

Below, if you see the number `1 and 2`, `3 and 4`. Eza uses colors from Terimal, but not `lla`.

![image](https://github.com/user-attachments/assets/a363e261-7eab-4ff4-a1fa-45c88f24e447)

Thanks for `lla`. 🧁 

```
~
🦄 systeminfo
OS: Fedora Linux 41 (Workstation Edition) x86_64
DE: GNOME 47.2
WM: Mutter (Wayland)

~
🦄 lla --version
lla 0.3.8
```

**Comment by azzamsa** [comment]
My bad. Setting the theme to `none` solves this issue. I think, `none` should be the default. Most users expect any app inside the terminal to respect colors set/provided by terminal.

```diff
+ theme = "none"
```

**Comment by chaqchase** [comment]
Hey @azzamsa glad you got it to work as you've expected, indeed `none` will omit the use of any theme, due to `default` is the default theme shipped with lla, I will make that clear in the docs to make easier to know how to turn off the use of custom themes.
